# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DogWatcher < Formula
  desc "A TUI to manage processes in Stardog."
  homepage "https://github.com/noahgorstein/dog-watcher"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.2.0/dog-watcher_Darwin_x86_64.tar.gz"
      sha256 "7da2e5bcae28e1188f5e62c7470e22b79fb023f2aa8888b5830f42fb4c5491c7"

      def install
        bin.install "dog-watcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.2.0/dog-watcher_Darwin_arm64.tar.gz"
      sha256 "69c0f80a6acfd3de7fb6e78e6361111ddef0f86b607f3d70ef622a6bff599ad4"

      def install
        bin.install "dog-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.2.0/dog-watcher_Linux_arm64.tar.gz"
      sha256 "f10f897b77e737900bd22059f38a0a4e3a6ed674f731d279e2d80dbe20110f28"

      def install
        bin.install "dog-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.2.0/dog-watcher_Linux_x86_64.tar.gz"
      sha256 "95abd3b872836c7952f42c762526f6a67d908225e854321e6500f893c29ec410"

      def install
        bin.install "dog-watcher"
      end
    end
  end
end
