# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DogWatcher < Formula
  desc "A TUI to manage processes in Stardog."
  homepage "https://github.com/noahgorstein/dog-watcher"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.1.0/dog-watcher_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "89d2d89c1b6fd7f57ed9755519abfe5ac13c6902ce814efe1e4823812a658a6b"

      def install
        bin.install "dog-watcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.1.0/dog-watcher_0.1.0_Darwin_arm64.tar.gz"
      sha256 "082e1bf0a2e88e93f1178fa035656dae0e0c99b1fad5313af4e33d46370fdad4"

      def install
        bin.install "dog-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.1.0/dog-watcher_0.1.0_Linux_x86_64.tar.gz"
      sha256 "d8df5bfe8ef7256c62a660821e39fecdff00e83e70f03746ce4b1a3877aef266"

      def install
        bin.install "dog-watcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noahgorstein/dog-watcher/releases/download/v0.1.0/dog-watcher_0.1.0_Linux_arm64.tar.gz"
      sha256 "674fa9e76528d926c6e3114a61dfefca6fec0822d075c3011e423cad6d2d9f04"

      def install
        bin.install "dog-watcher"
      end
    end
  end
end
