# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GuardDog < Formula
  desc "A TUI to manage users, roles, and permissions in Stardog."
  homepage "https://github.com/noahgorstein/guard-dog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/guard-dog/releases/download/v0.1.0/guard-dog_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "488f382e0703e67f288b83eb57b063188486618e07478e60f751da51bce16f62"

      def install
        bin.install "guard-dog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noahgorstein/guard-dog/releases/download/v0.1.0/guard-dog_0.1.0_Darwin_arm64.tar.gz"
      sha256 "9b841becb96cbe817bbf130daad44a9b17fabfcebd9c607fbfbe45439e344e47"

      def install
        bin.install "guard-dog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noahgorstein/guard-dog/releases/download/v0.1.0/guard-dog_0.1.0_Linux_arm64.tar.gz"
      sha256 "c0fec76e98fa9addfdc59fffe5132ff05f09d76732d97d1c0b82142230ad9f3b"

      def install
        bin.install "guard-dog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/guard-dog/releases/download/v0.1.0/guard-dog_0.1.0_Linux_x86_64.tar.gz"
      sha256 "9a3973a0a164dc90383510941f8abccafaa8ef812ef531b9d2d9ca47e6a62a9a"

      def install
        bin.install "guard-dog"
      end
    end
  end
end
