# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqp < Formula
  desc "a TUI playground to experiment and play with jq"
  homepage "https://github.com/noahgorstein/jqp"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.3.0/jqp_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "f42c88a083dbc6e36bc4ff25071a665768f1e88f7fe3466f230dd1c3279d087b"

      def install
        bin.install "jqp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.3.0/jqp_0.3.0_Darwin_arm64.tar.gz"
      sha256 "e99105a12bbbb5c92339c71022fb571c51e9ba73299ef7b535851494d1e66d96"

      def install
        bin.install "jqp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.3.0/jqp_0.3.0_Linux_arm64.tar.gz"
      sha256 "d98e27e588112dca7249d613bcbe6b53071543a9de138fc8e1ecb08781ce459e"

      def install
        bin.install "jqp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.3.0/jqp_0.3.0_Linux_x86_64.tar.gz"
      sha256 "9ce831b694d2ecb186259aa331aa4db97a88a5f4ea14d15910472b9d167f068a"

      def install
        bin.install "jqp"
      end
    end
  end
end
