# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jqp < Formula
  desc "a TUI playground to experiment and play with jq"
  homepage "https://github.com/noahgorstein/jqp"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.6.0/jqp_Darwin_x86_64.tar.gz"
      sha256 "351ecae85152733c61f33deed408822710f7f9192d3f8dbb0aade4afd7624ad6"

      def install
        bin.install "jqp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.6.0/jqp_Darwin_arm64.tar.gz"
      sha256 "826b189a9c4dd51f1c01d35800f65f22d3771535e821dd636974e764cb0863aa"

      def install
        bin.install "jqp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.6.0/jqp_Linux_x86_64.tar.gz"
      sha256 "77ca6bf04e4840191b9c29988bc30885606f9b2610c4a640f4686ad9d7ede102"

      def install
        bin.install "jqp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noahgorstein/jqp/releases/download/v0.6.0/jqp_Linux_arm64.tar.gz"
      sha256 "e7868da8eb7846baa72644522fc92fd7c88a8c38fdde84caf31ea98e0b5ca2f0"

      def install
        bin.install "jqp"
      end
    end
  end
end
